{{ if .Values.ui.install }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memgraph-ui
  name: memgraph-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgraph-ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memgraph-ui
    spec:
      containers:
      - name: memgraph-ui
        env:
        - name: QUICK_CONNECT_MG_HOST
          value: memgraph-main
        - name: QUICK_CONNECT_MG_PORT
          value: "7687"
        image: {{ .Values.ui.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: tcp-3000
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memgraph-ui
  name: memgraph-ui
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: memgraph-ui
{{ end }}
