apiVersion: devx.cisco.com/v1alpha1
kind: Workload
metadata:
  name: wld1
spec:
  api:
    prefix: /api/wld1
  components:
  - name: c1
    repo: pulumi_references
    path: reference/onedevx_replica
  - name: c2
    repo: pulumi_references
    path: workloads_replica/components
