apiVersion: devx.cisco.com/v1alpha1
kind: Component
metadata:
  name: c8
spec:
  type: image
  lifeCycle: Permanent
  dependencies:
    workloads:
      - core
  image:
    repository: nginxinc/nginx-unprivileged
    tag: "1.27.0"
    # repository: containers.cisco.com/devx/foo
    # tag: ""
  api:
    rest:
      - port: 7000
        scope: public
        name: hoo
        endpoints:
          - type: data
            path: /core/data8
      - port: 3000
        scope: private
        name: poo
        endpoints:
          - type: pvt
            path: /core/pvt