apiVersion: devx.cisco.com/v1alpha1
kind: Component
metadata:
  name: t2
spec:
  type: image
  lifeCycle: Permanent
  image:
    repository: k3d-myreg:5000/app1
    tag: "latest"
  api:
    rest:
      - port: 8000
        dapr: true
        scope: internal
        name: roo
        endpoints:
          - type: transactions
            path: /core/transactions3

  volumes:
    - name: tmp
      type: empty
      mountPath: /tmp

